INSERT INTO strain(id, title, description, src, rating, medical, energy, type_id) VALUES
(1, 'Nothern Lights', 'Northern Lights, also known as "NL," is an indica marijuana strain made by crossing Afghani with Thai. Northern Lights produces euphoric effects that settle in firmly throughout the body, relaxing muscles and easing the mind. Consumers say this strain has a pungently sweet and spicy flavor profile that is smooth on the exhale. Medical marijuana patients choose Northern Lights to help relieve symptoms associated with depression, stress, pain and insomnia. Growers say this strain features purple and crystal-coated buds and grows best indoors with a flowering time of 45-50 days.', './nothern_lights.png', 4, 'Medical', 20, 1),
(2, 'Strawberry Cough', 'Known for its sweet smell of fresh strawberries and an expanding sensation that can make even the most seasoned consumer cough, Strawberry Cough is a potent sativa marijuana strain with mysterious genetic origins. However, Strawberry Cough is thought to be a cross of Haze and Strawberry Fields.', 'strawberry_cough.png', 5, 'Medical', 70, 2),
(3, 'Purple Punch', 'Purple Punch is the sweet and sedating union of two indica-dominant classics. By breeding Larry OG with Granddaddy Purple, the astonishing trichome laden Purple Punch was born, smelling of grape candy, blueberry muffins, and tart Kool-Aid.', './purple_punch.png', 4, 'Medical', 20, 1),
(4, 'Super Lemon Haze', 'Super Lemon Haze, sometimes called "SLH," is a sativa-dominant hybrid marijuana strain of Lemon Skunk and Super Silver Haze and two time Cannabis Cup winner from Green House Seeds. Super Lemon Haze is a kief-caked multi-colored wonder. As the name states this strain has real lemony characteristics. The smell is zesty, citrusy, and a little sweet.', './super_lemon_haze.png', 5, 'Medical', 95, 3)


INSERT INTO strain_type(id, title, src, origin, description, ratio, effects) VALUES
(1, 'Indica', './indica1.webp', 'Origin: Cannabis indica is native to Afghanistan, India, Pakistan, and Turkey. The plants have adapted to the often harsh, dry, and turbulent climate of the Hindu Kush mountains.', 'Plant description: Indica plants are short and stocky with bushy greenery and chunky leaves that grow wide and broad. They grow faster than sativa, and each plant produces more buds.', 'Typical CBD to THC ratio: Indica strains often have higher levels of CBD, but the THC content isn’t necessarily less.', 'Commonly associated effects of use: Indica is sought after for its intensely relaxing effects. It may also help reduce nausea and pain and increase appetite.'),
(2, 'Sativa', './sativa.png', 'Cannabis sativa is found primarily in hot, dry climates with long sunny days. These include Africa, Central America, Southeast Asia, and portions of Western Asia', 'Sativa plants are tall and thin with finger-like leaves. They can grow taller than 12 feet, and they take longer to mature than some other types of cannabis.', 'Sativa often has lower doses of CBD and higher doses of THC.', 'Sativa often produces a “mind high,” or an energizing, anxiety-reducing effect. If you use sativa-dominant strains, you may feel productive and creative, not relaxed and lethargic.'),
(3, 'Hybrid', './hybrid.jpg', 'Hybrids are typically grown on farms or in greenhouses from a combination of sativa and indica strains.', 'The appearance of hybrid strains depends on the combination of the parent plants.', 'Many hybrid cannabis plants are grown in order to increase the THC percentage, but each type has a unique ratio of the two cannabinoids.', 'Farmers and producers select hybrids for their unique impacts. They can range from reducing anxiety and stress to easing symptoms of chemotherapy or radiation.');
